### PR TITLE
Return 0 for window if server side rendering

### PR DESCRIPTION
**Pull request by Ionut-Milas**
This will enable the use if the component with server side rendering

### CODE REVIEW

**Comment by fritz-c** [comment]
Thanks a bunch for this! Let me know if this helps solve #27. I haven't really had the time or the environment to confirm whether this will work with SSR.

**Comment by im-fortech** [comment]
Solved one problem but hit another one.. Now it crashes at: `window.navigator.userAgent.toLowerCase()` seems a dependency that handles IE stuff...

**Comment by fritz-c** [comment]
@im-fortech Would you mind checking it now? With v3.2.2, I searched out other instances of `window` and skipped those segments when necessary.

**Comment by im-fortech** [comment]
node_modules/react-image-lightbox/dist/umd/react-image-lightbox.js:1190
            return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
                                       ^

ReferenceError: window is not defined

/react-image-lightbox/dist/umd/webpack:/~/style-loader/addStyles.js:14:1
/react-image-lightbox/dist/umd/webpack:/~/style-loader/addStyles.js:9:1
/react-image-lightbox/dist/umd/webpack:/~/style-loader/addStyles.js:31:1

**Comment by fritz-c** [comment]
@im-fortech 
Ahh, `style-loader`... I knew that was going to be an issue eventually.
I tried for a little bit to switch to external CSS, but wasn't having much luck with the webpack config. It might be a while yet before I can get time to work on this.

**Pull request merged**
