### PR TITLE
Make toolbar layout flexible

### PR DESCRIPTION
**Pull request by ohtake**
1. Do not wrap toolbar buttons in small screen
before:
before1
after:
after1

2. Show title as wide as possible in large screen
before:
before2
after:
after2

### CODE REVIEW

**Comment by fritz-c** [comment]
This looks excellent, but I'm concerned about [IE support](http://caniuse.com/#feat=flexbox). Could you modify it so the previously implemented IE-compatible styles are used when the browser is IE?

**Comment by ohtake** [comment]
IE 11 partially supports flex box and works fine.

untitled

According to the link you provided, IE 10 and old Webkit require vendor prefixes for flex box.
I will add prefixes after I find an environment with old browsers.

Another implementation which does not require flex box is <https://github.com/ohtake/sanrio-wardrobe/commit/6e3587c5bb3092112ee286adf2f14e73fabfdf59>.
But it requires toolbar width calculation (line 22) and is hard to use.

**Comment by ohtake** [comment]
IE 10 (emulated by IE 11 on Windows 10) works fine without vendor prefix.
It is strange because Caniuse says IE 10 requires `-ms-` prefix, but it works.

IE 9 (emulated by IE 11 on Windows 10) has an issue that
toolbar buttons are displayed at left in the next line.

I also tried another approach: the 'table layout' technics in Web 1.0 era
which uses table element to layout elements.
HTML gets ugly and there is some issue on overflow.
The 'table layout' does not solve the issue.

If you want to support IE 9, please reject this PR.

**Comment by fritz-c** [comment]
I've built off of your code and implemented the fallback as I had envisioned it in #8. Any thoughts?

**Comment by ohtake** [comment]
Great. It works on IE9.

I think IE10 and IE11 may use flexbox.
IE11 supports flexbox partially.
IE10 supports old flexbox spec.
[Inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer), a dependency of Radium, translates standard flex box definition to old spec.
That is why IE10 works fine without modifying stylesheet.

`function isIE` could be `isIE9orOlder` or something like that.

**Comment by fritz-c** [comment]
@ohtake I just added a commit to do just that. Could you test it out?

**Comment by ohtake** [comment]
It works perfectly. Thanks.

IE11 and IE10 use flex boxes.
IE9 works as it was.

IE 11, 10, and 9

**Comment by fritz-c** [comment]
Thanks for checking! I guess I'll merge this PR followed by mine.

**Comment by fritz-c** [comment]
This is now available in v2.2.0! Thanks for the help!

**Pull request merged**
