### PR TITLE
Updated repo with ImageLoad handler and fixed an issue when lightbox is used in an iframe

### PR DESCRIPTION
**Pull request by pborawski78**
I also updated webpack to test something, you can revert that. Basically I just added a image loaded handler and am only using window.top when window.self == window.top to fix an error when this is used in an iframe. Both of these solutions are addressing issues #103 and #102 respectively.

### CODE REVIEW

**Comment by fritz-c** [comment]
Thanks for the contribution! I cleaned things up a bit, but it's nice to have a foundation to build on. These are available now in v4.6.0

**Comment by pborawski78** [comment]
Thanks! What did you clean up exactly?

Also I'm new to contributing and forking, so I don't understand how the
build process works from the forked repo when I imported that into my react
app. What I mean is, when I imported your repo, it creates the js file in
the dist folder but my version didn't do that. So I just ran build from the
forked repo and copied the dist folder directly into the node modules in my
react app.

Thanks for accepting the code and cleaning it up for me. Much appreciated!

**Comment by fritz-c** [comment]
My changes:
https://github.com/fritz-c/react-image-lightbox/compare/8ba1887f2643dd8a8b3adeab96ed92cef4a165e3...master

As for local development, I think you'd have to use [`npm link`](https://docs.npmjs.com/cli/link) to use an unreleased library with your changes.

If there's something I want to test out, though, I usually just make a test case or another example within the library repo. I do that more for my react-sortable-tree repo with the storybook examples, for example. 

If you're talking about forking the library to permanently use your changes, you could create your own npm library using this code as a base, plus your modifications. You might [scope the package](https://docs.npmjs.com/misc/scope) with your user name to make it more obvious it's a fork.

**Comment by pborawski78** [comment]
Liked the changes you made and thanks a lot for the tips. You've been a
great help! I'm happy I could help contribute to this project. I've tried
to make my own  Version of this and used other modal/lightbox  solutions
out there, and this is the best one I've found by far. Keep up the good
work and have a great night!

**Pull request merged**
